api:
  dashboard: true
  insecure: true

ping: {}

providers:
  file:
    directory: /etc/traefik/conf
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  internal:
    address: :8001
  traefik:
    address: :8080
  websecure:
    address: :443

log:
  filePath: './logs/traefik.log'

accessLog:
  filePath: './logs/access.log'
